# Generated by Django 4.1.6 on 2023-03-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='claveHorario',
            new_name='clave',
        ),
    ]
