# Generated by Django 4.1.6 on 2023-02-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.SmallIntegerField(verbose_name='Creditos')),
                ('semestre', models.CharField(choices=[(1, '1er semestre'), (2, '2do semestre'), (3, '3er semestre'), (4, '4to semestre'), (5, '5to semestre'), (6, '6to semestre'), (7, '7mo semestre'), (8, '8vo semestre'), (9, '9no semestre')], max_length=2)),
                ('optativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MateriasPrecendentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_actual', to='materias.materia', verbose_name='Materia')),
                ('materia_precedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_precedente', to='materias.materia', verbose_name='Materia')),
            ],
        ),
    ]
