# Generated by Django 4.1.6 on 2023-02-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.CharField(choices=[('1', '1er semestre'), ('2', '2do semestre'), ('3', '3er semestre'), ('4', '4to semestre'), ('5', '5to semestre'), ('6', '6to semestre'), ('7', '7mo semestre'), ('8', '8vo semestre'), ('9', '9no semestre')], max_length=2),
        ),
    ]
